/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Database.DBConnection;
import Model.Patient;
import Views.AdminGUI.AdminDashBoardGUI;
import Views.PatientGUI.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sajib
 */
public class HomePagePatientLoginGUI extends javax.swing.JFrame {

    int viewEyeFlag = 1;
    public static int LogINPatientID;
    Patient p;
    Connection con = DBConnection.getConnection();
    PreparedStatement ps;
    ResultSet rs;
    public HomePagePatientLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientPasswordField = new javax.swing.JPasswordField();
        PatientIdField = new javax.swing.JTextField();
        MouseClickBackPatientDashBoardLEFT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardTOP = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardBOTTOM = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardRIGHT = new javax.swing.JLabel();
        ShowPassword = new javax.swing.JLabel();
        ForgetPassword = new javax.swing.JLabel();
        SignUp = new javax.swing.JLabel();
        Login = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientPasswordField.setBackground(new java.awt.Color(49, 19, 50));
        PatientPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PatientPasswordField.setBorder(null);
        getContentPane().add(PatientPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 298, 181, 20));

        PatientIdField.setBackground(new java.awt.Color(49, 19, 50));
        PatientIdField.setForeground(new java.awt.Color(255, 255, 255));
        PatientIdField.setBorder(null);
        getContentPane().add(PatientIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 201, 201, 20));

        MouseClickBackPatientDashBoardLEFT.setPreferredSize(new java.awt.Dimension(310, 466));
        MouseClickBackPatientDashBoardLEFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardLEFTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        MouseClickBackPatientDashBoardTOP.setPreferredSize(new java.awt.Dimension(900, 42));
        MouseClickBackPatientDashBoardTOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardTOPMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardTOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MouseClickBackPatientDashBoardBOTTOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardBOTTOMMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardBOTTOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 508, 900, 42));

        MouseClickBackPatientDashBoardRIGHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardRIGHTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 42, 308, 466));

        ShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ShowPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(ShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 299, 16, 16));

        ForgetPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ForgetPasswordMouseClicked(evt);
            }
        });
        getContentPane().add(ForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 341, 90, 16));

        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMouseClicked(evt);
            }
        });
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 446, 74, 27));

        Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginMouseClicked(evt);
            }
        });
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 386, 64, 30));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HomaPagePatientLoginGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void MouseClickBackPatientDashBoardLEFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardLEFTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardLEFTMouseClicked

    private void MouseClickBackPatientDashBoardTOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardTOPMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardTOPMouseClicked

    private void MouseClickBackPatientDashBoardBOTTOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked

    private void MouseClickBackPatientDashBoardRIGHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked

    private void ShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShowPasswordMouseClicked
        if(viewEyeFlag % 2 == 1)
            PatientPasswordField.setEchoChar((char)0);
        else
            PatientPasswordField.setEchoChar('*');
        viewEyeFlag++;
    }//GEN-LAST:event_ShowPasswordMouseClicked

    private void ForgetPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForgetPasswordMouseClicked
        new HomePagePatientForgetPasswordGUI().setVisible(true);
    }//GEN-LAST:event_ForgetPasswordMouseClicked

    private void SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseClicked
        new PatientSignUpGUI().setVisible(true);
    }//GEN-LAST:event_SignUpMouseClicked

    private void LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginMouseClicked
        
        p = new Patient();
        if(PatientIdField.getText().equals("") && PatientPasswordField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please Input ID and Password");
        else if(PatientIdField.getText().equals("") && !(PatientPasswordField.getText().equals("")))
            JOptionPane.showMessageDialog(null,"Please Input ID");
        else if(!(PatientIdField.getText().equals("")) && PatientPasswordField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please Input Password");
        else {
            if(con != null) {
                try {
                    ps = con.prepareStatement("SELECT * FROM patient");
                    rs = ps.executeQuery();
                    boolean flag = true;
                    while(rs.next()) {
                        p.initValue(rs);
                        if(String.valueOf(p.getID()).equals(PatientIdField.getText()) && p.getPassword().equals(PatientPasswordField.getText())) {
                            LogINPatientID = p.getID();
                            new PatientDashBoardGUI().setVisible(true);
                            flag = false;
                            break;
                            //this.setVisible(false);
                        }
                        else {
                            if(String.valueOf(p.getID()).equals(PatientIdField.getText()) && !(p.getPassword().equals(PatientPasswordField.getText()))) {
                                JOptionPane.showMessageDialog(null,"Wrong Password");
                                flag = false;
                                break;
                            }
                        }
                    }
                    if(flag) {
                        JOptionPane.showMessageDialog(null,"Wrong ID And Password");
                    }
                }
                catch(Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }               
            }
            else
                JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
        }
        
        
    }//GEN-LAST:event_LoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePagePatientLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePagePatientLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePagePatientLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePagePatientLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePagePatientLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JLabel ForgetPassword;
    private javax.swing.JLabel Login;
    private javax.swing.JLabel MouseClickBackPatientDashBoardBOTTOM;
    private javax.swing.JLabel MouseClickBackPatientDashBoardLEFT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardRIGHT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardTOP;
    private javax.swing.JTextField PatientIdField;
    private javax.swing.JPasswordField PatientPasswordField;
    private javax.swing.JLabel ShowPassword;
    private javax.swing.JLabel SignUp;
    // End of variables declaration//GEN-END:variables
}
