/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author sajib
 */
public class HomePageContactUsGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomePageContactUsGUI
     */
    public HomePageContactUsGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Send = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        MouseClickBackPatientDashBoardLEFT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardTOP = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardBOTTOM = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardRIGHT = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Send, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 459, 53, 30));

        NameField.setBackground(new java.awt.Color(69, 44, 71));
        NameField.setForeground(new java.awt.Color(255, 255, 255));
        NameField.setBorder(null);
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 151, 220, 14));

        EmailField.setBackground(new java.awt.Color(69, 44, 71));
        EmailField.setForeground(new java.awt.Color(255, 255, 255));
        EmailField.setBorder(null);
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 206, 220, 14));

        jScrollPane1.setViewportView(jTextPane1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 276, 272, 170));

        MouseClickBackPatientDashBoardLEFT.setPreferredSize(new java.awt.Dimension(310, 466));
        MouseClickBackPatientDashBoardLEFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardLEFTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        MouseClickBackPatientDashBoardTOP.setPreferredSize(new java.awt.Dimension(900, 42));
        MouseClickBackPatientDashBoardTOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardTOPMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardTOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MouseClickBackPatientDashBoardBOTTOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardBOTTOMMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardBOTTOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 508, 900, 42));

        MouseClickBackPatientDashBoardRIGHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardRIGHTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 42, 270, 466));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HomaPageContactUsGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void MouseClickBackPatientDashBoardLEFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardLEFTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardLEFTMouseClicked

    private void MouseClickBackPatientDashBoardTOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardTOPMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardTOPMouseClicked

    private void MouseClickBackPatientDashBoardBOTTOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked

    private void MouseClickBackPatientDashBoardRIGHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageContactUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageContactUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageContactUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageContactUsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageContactUsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel MouseClickBackPatientDashBoardBOTTOM;
    private javax.swing.JLabel MouseClickBackPatientDashBoardLEFT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardRIGHT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardTOP;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel Send;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
