/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Model.Admin;
import Views.AdminGUI.*;
import javax.swing.JOptionPane;

/**
 *
 * @author sajib
 */
public class HomePageAdminLoginGUI extends javax.swing.JFrame {
    
    Admin ad;
    int eyeFlag = 1;
    public static int logedINAdminID;
//    public static String adminIDField;
//    public static String passwordField;
    public HomePageAdminLoginGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MouseClickBackPatientDashBoardRIGHT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardBOTTOM = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardTOP = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardLEFT = new javax.swing.JLabel();
        AdminID = new javax.swing.JTextField();
        AdminLoginLabel = new javax.swing.JLabel();
        AdminShowPasswordLabel = new javax.swing.JLabel();
        AdminForgetPasswordLabel = new javax.swing.JLabel();
        AdminPasswordField = new javax.swing.JPasswordField();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MouseClickBackPatientDashBoardRIGHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardRIGHTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 42, 308, 466));

        MouseClickBackPatientDashBoardBOTTOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardBOTTOMMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardBOTTOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 508, 900, 42));

        MouseClickBackPatientDashBoardTOP.setPreferredSize(new java.awt.Dimension(900, 42));
        MouseClickBackPatientDashBoardTOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardTOPMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardTOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MouseClickBackPatientDashBoardLEFT.setPreferredSize(new java.awt.Dimension(310, 466));
        MouseClickBackPatientDashBoardLEFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardLEFTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        AdminID.setBackground(new java.awt.Color(49, 19, 50));
        AdminID.setForeground(new java.awt.Color(255, 255, 255));
        AdminID.setBorder(null);
        getContentPane().add(AdminID, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 201, 201, 20));

        AdminLoginLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLoginLabelMouseClicked(evt);
            }
        });
        getContentPane().add(AdminLoginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 386, 64, 30));

        AdminShowPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminShowPasswordLabelMouseClicked(evt);
            }
        });
        getContentPane().add(AdminShowPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 299, 16, 16));

        AdminForgetPasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminForgetPasswordLabelMouseClicked(evt);
            }
        });
        getContentPane().add(AdminForgetPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 341, 90, 16));

        AdminPasswordField.setBackground(new java.awt.Color(49, 19, 50));
        AdminPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        AdminPasswordField.setBorder(null);
        getContentPane().add(AdminPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 298, 181, 20));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/HomaPageAdminLoginGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClickBackPatientDashBoardRIGHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked

    private void MouseClickBackPatientDashBoardBOTTOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked

    private void MouseClickBackPatientDashBoardTOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardTOPMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardTOPMouseClicked

    private void MouseClickBackPatientDashBoardLEFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardLEFTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardLEFTMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void AdminShowPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminShowPasswordLabelMouseClicked
        if(eyeFlag % 2 == 1) {
            AdminPasswordField.setEchoChar((char)0);
        }
        else
            AdminPasswordField.setEchoChar('*');
        eyeFlag++;
    }//GEN-LAST:event_AdminShowPasswordLabelMouseClicked

    private void AdminForgetPasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminForgetPasswordLabelMouseClicked
        new HomePageAdminForgetPasswordGUI().setVisible(true);
    }//GEN-LAST:event_AdminForgetPasswordLabelMouseClicked

    private void AdminLoginLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLoginLabelMouseClicked
        ad = new Admin();
        if(AdminID.getText().equals("") && AdminPasswordField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please Input ID and Password");
        else if(AdminID.getText().equals("") && !(AdminPasswordField.getText().equals("")))
            JOptionPane.showMessageDialog(null,"Please Input ID");
        else if(!(AdminID.getText().equals("")) && AdminPasswordField.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please Input Password");
        else {
            if(String.valueOf(ad.getID()).equals(AdminID.getText()) && ad.getPassword().equals(AdminPasswordField.getText())) {
                logedINAdminID = ad.getID();
                new AdminDashBoardGUI().setVisible(true);
                //this.setVisible(false);
            }
            else {
                if(!(String.valueOf(ad.getID()).equals(AdminID.getText())) && ad.getPassword().equals(AdminPasswordField.getText()))
                    JOptionPane.showMessageDialog(null,"Wrong ID");
                else if(String.valueOf(ad.getID()).equals(AdminID.getText()) && !(ad.getPassword().equals(AdminPasswordField.getText())))
                    JOptionPane.showMessageDialog(null,"Wrong Password");
                else
                    JOptionPane.showMessageDialog(null,"Wrong ID and Password");
            }
        }
        
    }//GEN-LAST:event_AdminLoginLabelMouseClicked
    
//    private void initTextField() {
//        adminIDField = AdminID.getText();
//        passwordField = AdminPasswordField.getText();
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePageAdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePageAdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePageAdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePageAdminLoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePageAdminLoginGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminForgetPasswordLabel;
    private javax.swing.JTextField AdminID;
    private javax.swing.JLabel AdminLoginLabel;
    private javax.swing.JPasswordField AdminPasswordField;
    private javax.swing.JLabel AdminShowPasswordLabel;
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JLabel MouseClickBackPatientDashBoardBOTTOM;
    private javax.swing.JLabel MouseClickBackPatientDashBoardLEFT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardRIGHT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardTOP;
    // End of variables declaration//GEN-END:variables
}
