/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.AdminGUI;

import Database.DBConnection;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sajib
 */
public class AdminDashBoardPatientTestDetailsGUI extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    String selected_PatientID;
    public static String selected_app_no;
    public static String selected_TestID;
    public AdminDashBoardPatientTestDetailsGUI() {
        initComponents();
        con = DBConnection.getConnection();
        setIDField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientID = new javax.swing.JComboBox<>();
        IOANoCombo = new javax.swing.JComboBox<>();
        MouseClickBackPatientDashBoardRIGHT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardBOTTOM = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardLEFT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardTOP = new javax.swing.JLabel();
        TestID = new javax.swing.JTextField();
        Cost = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        Submit = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Patient ID" }));
        PatientID.setBorder(null);
        PatientID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PatientIDItemStateChanged(evt);
            }
        });
        getContentPane().add(PatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 126, 130, 35));

        IOANoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select IOA No" }));
        IOANoCombo.setBorder(null);
        IOANoCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IOANoComboItemStateChanged(evt);
            }
        });
        IOANoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IOANoComboActionPerformed(evt);
            }
        });
        getContentPane().add(IOANoCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 184, 130, 35));

        MouseClickBackPatientDashBoardRIGHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardRIGHTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 42, 308, 466));

        MouseClickBackPatientDashBoardBOTTOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardBOTTOMMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardBOTTOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 508, 900, 42));

        MouseClickBackPatientDashBoardLEFT.setPreferredSize(new java.awt.Dimension(310, 466));
        MouseClickBackPatientDashBoardLEFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardLEFTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        MouseClickBackPatientDashBoardTOP.setPreferredSize(new java.awt.Dimension(900, 42));
        MouseClickBackPatientDashBoardTOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardTOPMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardTOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        TestID.setBackground(new java.awt.Color(49, 19, 50));
        TestID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TestID.setForeground(new java.awt.Color(255, 255, 255));
        TestID.setBorder(null);
        getContentPane().add(TestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 252, 200, 23));

        Cost.setBackground(new java.awt.Color(49, 19, 50));
        Cost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cost.setForeground(new java.awt.Color(255, 255, 255));
        Cost.setBorder(null);
        getContentPane().add(Cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 360, 200, 23));

        Type.setBackground(new java.awt.Color(49, 19, 50));
        Type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setBorder(null);
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 306, 200, 23));

        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 406, 53, 30));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdminImg/AdminDashBoardPatientTestDetailsGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClickBackPatientDashBoardRIGHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked

    private void MouseClickBackPatientDashBoardBOTTOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked

    private void MouseClickBackPatientDashBoardLEFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardLEFTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardLEFTMouseClicked

    private void MouseClickBackPatientDashBoardTOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardTOPMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardTOPMouseClicked

    private void IOANoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IOANoComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IOANoComboActionPerformed

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        new AdminDashBoardAddPatientTestDetailsGUI().setVisible(true);
    }//GEN-LAST:event_SubmitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void PatientIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PatientIDItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            if(PatientID.getSelectedIndex()>0){
                selected_PatientID = PatientID.getSelectedItem().toString();
                setIOANo();
            }
        }
    }//GEN-LAST:event_PatientIDItemStateChanged

    private void IOANoComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IOANoComboItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            if(IOANoCombo.getSelectedIndex()>0){
                selected_app_no = IOANoCombo.getSelectedItem().toString();
                setTestIDAndTypeAndCost();
            }
        }
    }//GEN-LAST:event_IOANoComboItemStateChanged

    private void setTestIDAndTypeAndCost() {
        if(con != null) {
            try {
                ps = con.prepareStatement("SELECT a.t_id,type,cost FROM appointment a, test t where a.app_no = ? and a.t_id = t.t_id");
                ps.setInt(1, Integer.valueOf(selected_app_no));
                rs = ps.executeQuery();
                
                rs.next();
                TestID.setText(rs.getString(1));
                selected_TestID = TestID.getText();
                Type.setText(rs.getString(2));
                Cost.setText(String.valueOf(rs.getString(3)));
                
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
    }
    
    private void setIOANo() {
        if(con != null) {
            try {
                ps = con.prepareStatement("SELECT app_no FROM appointment where p_id = ?");
                ps.setInt(1, Integer.valueOf(selected_PatientID));
                rs = ps.executeQuery();
                
                IOANoCombo.removeAllItems();
                IOANoCombo.addItem("Select IOA No");
                while(rs.next()) {
                    IOANoCombo.addItem(String.valueOf(rs.getInt(1)));
                }
                
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
    }
    
    private void setIDField() {
        if(con != null) {
            try {
                ps = con.prepareStatement("SELECT * FROM patient");
                rs = ps.executeQuery();
                while(rs.next()) {
                    PatientID.addItem(String.valueOf(rs.getInt(1)));
                }
                
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardPatientTestDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardPatientTestDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardPatientTestDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardPatientTestDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoardPatientTestDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JTextField Cost;
    private javax.swing.JComboBox<String> IOANoCombo;
    private javax.swing.JLabel MouseClickBackPatientDashBoardBOTTOM;
    private javax.swing.JLabel MouseClickBackPatientDashBoardLEFT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardRIGHT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardTOP;
    private javax.swing.JComboBox<String> PatientID;
    private javax.swing.JLabel Submit;
    private javax.swing.JTextField TestID;
    private javax.swing.JTextField Type;
    // End of variables declaration//GEN-END:variables
}
