/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.AdminGUI;

import javax.swing.JFrame;

/**
 *
 * @author sajib
 */
public class AdminDashBoardGUI extends javax.swing.JFrame {

    int viewFlag = 1;
    
    public AdminDashBoardGUI() {
        initComponents();
        AdminSettingView.setEnabled(false);
        AdminSettingView.setVisible(false);
        
        AdminSettingProfile.setEnabled(false);
        AdminSettingProfile.setVisible(false);
        
        AdminSettingChangePassword.setEnabled(false);
        AdminSettingChangePassword.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AdminAddTestDetails = new javax.swing.JLabel();
        AdminAddParametersDetails = new javax.swing.JLabel();
        AdminReports = new javax.swing.JLabel();
        AdminViewPatientAppointment = new javax.swing.JLabel();
        AdminPatientTestDetails = new javax.swing.JLabel();
        AdminLogOut = new javax.swing.JLabel();
        AdminSetting = new javax.swing.JLabel();
        AdminSettingProfile = new javax.swing.JLabel();
        AdminSettingChangePassword = new javax.swing.JLabel();
        AdminSettingView = new javax.swing.JLabel();
        MinimizeLabel = new javax.swing.JLabel();
        ClosedLabel = new javax.swing.JLabel();
        AdminSettingClick = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminAddTestDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminAddTestDetailsMouseClicked(evt);
            }
        });
        getContentPane().add(AdminAddTestDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 178, 140, 140));

        AdminAddParametersDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminAddParametersDetailsMouseClicked(evt);
            }
        });
        getContentPane().add(AdminAddParametersDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 178, 140, 140));

        AdminReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminReportsMouseClicked(evt);
            }
        });
        getContentPane().add(AdminReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 178, 140, 140));

        AdminViewPatientAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminViewPatientAppointmentMouseClicked(evt);
            }
        });
        getContentPane().add(AdminViewPatientAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 366, 140, 140));

        AdminPatientTestDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminPatientTestDetailsMouseClicked(evt);
            }
        });
        getContentPane().add(AdminPatientTestDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 366, 140, 140));

        AdminLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLogOutMouseClicked(evt);
            }
        });
        getContentPane().add(AdminLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 366, 140, 140));
        getContentPane().add(AdminSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 81, 24, 24));

        AdminSettingProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminSettingProfileMouseClicked(evt);
            }
        });
        getContentPane().add(AdminSettingProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 157, 80, 24));

        AdminSettingChangePassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminSettingChangePasswordMouseClicked(evt);
            }
        });
        getContentPane().add(AdminSettingChangePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(771, 198, 126, 24));

        AdminSettingView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdminImg/AdminSettingView.png"))); // NOI18N
        getContentPane().add(AdminSettingView, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 134, 185, 106));

        MinimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseClicked(evt);
            }
        });
        getContentPane().add(MinimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 8, 16, 16));

        ClosedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosedLabelMouseClicked(evt);
            }
        });
        getContentPane().add(ClosedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 8, 16, 16));

        AdminSettingClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminSettingClickMouseClicked(evt);
            }
        });
        getContentPane().add(AdminSettingClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(858, 81, 24, 24));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdminImg/AdminDashBoardGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MinimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeLabelMouseClicked

    private void ClosedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosedLabelMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_ClosedLabelMouseClicked

    private void AdminSettingClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminSettingClickMouseClicked
        if(viewFlag % 2 == 1) {
            AdminSettingView.setEnabled(true);
            AdminSettingView.setVisible(true);
            
            AdminSettingProfile.setEnabled(true);
            AdminSettingProfile.setVisible(true);
        
            AdminSettingChangePassword.setEnabled(true);
            AdminSettingChangePassword.setVisible(true);
        }
        else {
            AdminSettingView.setEnabled(false);
            AdminSettingView.setVisible(false);
            
            AdminSettingProfile.setEnabled(false);
            AdminSettingProfile.setVisible(false);
        
            AdminSettingChangePassword.setEnabled(false);
            AdminSettingChangePassword.setVisible(false);
        }
        viewFlag++;
    }//GEN-LAST:event_AdminSettingClickMouseClicked

    private void AdminSettingProfileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminSettingProfileMouseClicked
        new AdminDashBoardSettingProfileGUI().setVisible(true);
        AdminSettingProfile.setEnabled(false);
        AdminSettingProfile.setVisible(false);
        
        AdminSettingChangePassword.setEnabled(false);
        AdminSettingChangePassword.setVisible(false);
        
        AdminSettingView.setEnabled(false);
        AdminSettingView.setVisible(false);
        
        viewFlag = 1;
    }//GEN-LAST:event_AdminSettingProfileMouseClicked

    private void AdminSettingChangePasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminSettingChangePasswordMouseClicked
        new AdminDashBoardSettingChangePasswordGUI().setVisible(true);
        AdminSettingProfile.setEnabled(false);
        AdminSettingProfile.setVisible(false);
        
        AdminSettingChangePassword.setEnabled(false);
        AdminSettingChangePassword.setVisible(false);
        
        AdminSettingView.setEnabled(false);
        AdminSettingView.setVisible(false);
        
        viewFlag = 1;
    }//GEN-LAST:event_AdminSettingChangePasswordMouseClicked

    private void AdminAddTestDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminAddTestDetailsMouseClicked
        new AdminDashBoardAddTestDetailsGUI().setVisible(true);
    }//GEN-LAST:event_AdminAddTestDetailsMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void AdminAddParametersDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminAddParametersDetailsMouseClicked
        new AdminDashBoardAddParameterDetailsGUI().setVisible(true);
    }//GEN-LAST:event_AdminAddParametersDetailsMouseClicked

    private void AdminViewPatientAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminViewPatientAppointmentMouseClicked
        new AdminDashBoardViewPatientAppointmentDetailsGUI().setVisible(true);
    }//GEN-LAST:event_AdminViewPatientAppointmentMouseClicked

    private void AdminLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLogOutMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_AdminLogOutMouseClicked

    private void AdminReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminReportsMouseClicked
        new AdminDashBoardReportGUI().setVisible(true);
    }//GEN-LAST:event_AdminReportsMouseClicked

    private void AdminPatientTestDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminPatientTestDetailsMouseClicked
        new AdminDashBoardPatientTestDetailsGUI().setVisible(true);
    }//GEN-LAST:event_AdminPatientTestDetailsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminAddParametersDetails;
    private javax.swing.JLabel AdminAddTestDetails;
    private javax.swing.JLabel AdminLogOut;
    private javax.swing.JLabel AdminPatientTestDetails;
    private javax.swing.JLabel AdminReports;
    private javax.swing.JLabel AdminSetting;
    private javax.swing.JLabel AdminSettingChangePassword;
    private javax.swing.JLabel AdminSettingClick;
    private javax.swing.JLabel AdminSettingProfile;
    private javax.swing.JLabel AdminSettingView;
    private javax.swing.JLabel AdminViewPatientAppointment;
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JLabel ClosedLabel;
    private javax.swing.JLabel MinimizeLabel;
    // End of variables declaration//GEN-END:variables
}
