/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.AdminGUI;

import Database.DBConnection;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sajib
 */
public class AdminDashBoardAddParameterDetailsGUI extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    String selected_ID;
    
    public AdminDashBoardAddParameterDetailsGUI() {
        initComponents();
        con = DBConnection.getConnection();
        setIDField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ID = new javax.swing.JComboBox<>();
        Submit = new javax.swing.JLabel();
        Type = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Minimum = new javax.swing.JTextField();
        Maximum = new javax.swing.JTextField();
        MouseClickBackPatientDashBoardTOP = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardLEFT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardBOTTOM = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardRIGHT = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Test ID" }));
        ID.setBorder(null);
        ID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IDItemStateChanged(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(381, 131, 130, 35));

        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 390, 53, 30));

        Type.setBackground(new java.awt.Color(49, 19, 50));
        Type.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setBorder(null);
        Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeActionPerformed(evt);
            }
        });
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 199, 209, 14));

        Name.setBackground(new java.awt.Color(49, 19, 50));
        Name.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setBorder(null);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 248, 209, 14));

        Minimum.setBackground(new java.awt.Color(49, 19, 50));
        Minimum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Minimum.setForeground(new java.awt.Color(255, 255, 255));
        Minimum.setBorder(null);
        getContentPane().add(Minimum, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 297, 209, 14));

        Maximum.setBackground(new java.awt.Color(49, 19, 50));
        Maximum.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Maximum.setForeground(new java.awt.Color(255, 255, 255));
        Maximum.setBorder(null);
        getContentPane().add(Maximum, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 346, 209, 14));

        MouseClickBackPatientDashBoardTOP.setPreferredSize(new java.awt.Dimension(900, 42));
        MouseClickBackPatientDashBoardTOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardTOPMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardTOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MouseClickBackPatientDashBoardLEFT.setPreferredSize(new java.awt.Dimension(310, 466));
        MouseClickBackPatientDashBoardLEFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardLEFTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        MouseClickBackPatientDashBoardBOTTOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardBOTTOMMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardBOTTOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 508, 900, 42));

        MouseClickBackPatientDashBoardRIGHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardRIGHTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 42, 308, 466));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdminImg/AdminDashBoardAddParameterDetailsGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClickBackPatientDashBoardTOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardTOPMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardTOPMouseClicked

    private void MouseClickBackPatientDashBoardLEFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardLEFTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardLEFTMouseClicked

    private void MouseClickBackPatientDashBoardBOTTOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked

    private void MouseClickBackPatientDashBoardRIGHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void IDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IDItemStateChanged
        if(con != null) {
            try {
                selected_ID = ID.getItemAt(ID.getSelectedIndex());
                ps = con.prepareStatement("SELECT * FROM `test` WHERE t_id = ?");
                ps.setInt(1,Integer.valueOf(selected_ID));
                rs = ps.executeQuery();
                rs.next();
                Type.setText(rs.getString(2));
                
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
        
    }//GEN-LAST:event_IDItemStateChanged

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        if(Name.getText().equals("") || Minimum.getText().equals("") || Maximum.getText().equals(""))
            JOptionPane.showMessageDialog(null,"Please Fill Up All Data");
        else {
            if(con != null) {
                try {
                    ps = con.prepareStatement("INSERT INTO `test_details`(`name`, `minimum`, `maximum`, `t_id`) VALUES (?,?,?,?)");
                    ps.setInt(4,Integer.valueOf(selected_ID));
                    ps.setString(1,Name.getText());
                    ps.setString(2,Minimum.getText());
                    ps.setString(3,Maximum.getText());
                    
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Parameter Added");
                    this.setVisible(false);
                }
                catch(Exception ex) {
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }               
            }
            else
                JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
        }
    }//GEN-LAST:event_SubmitMouseClicked
 
    private void setIDField() {
        if(con != null) {
            try {
                ps = con.prepareStatement("SELECT * FROM TEST");
                rs = ps.executeQuery();
                
                while(rs.next()) {
                    ID.addItem(String.valueOf(rs.getInt(1)));
                }
                
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardAddParameterDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardAddParameterDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardAddParameterDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardAddParameterDetailsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoardAddParameterDetailsGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JComboBox<String> ID;
    private javax.swing.JTextField Maximum;
    private javax.swing.JTextField Minimum;
    private javax.swing.JLabel MouseClickBackPatientDashBoardBOTTOM;
    private javax.swing.JLabel MouseClickBackPatientDashBoardLEFT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardRIGHT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardTOP;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Submit;
    private javax.swing.JTextField Type;
    // End of variables declaration//GEN-END:variables
}
