/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.AdminGUI;

import Database.DBConnection;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author sajib
 */
public class AdminDashBoardReportGUI extends javax.swing.JFrame {

    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    protected static String selected_TestID;
    protected static String selected_App_No;
    
    public AdminDashBoardReportGUI() {
        initComponents();
        con = DBConnection.getConnection();
        setIDField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TestID = new javax.swing.JComboBox<>();
        IOANo = new javax.swing.JComboBox<>();
        PatientID = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        Submit = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardRIGHT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardBOTTOM = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardLEFT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardTOP = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TestID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Test ID" }));
        TestID.setBorder(null);
        TestID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TestIDItemStateChanged(evt);
            }
        });
        getContentPane().add(TestID, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 117, 130, 35));

        IOANo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select IOA No" }));
        IOANo.setBorder(null);
        IOANo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                IOANoItemStateChanged(evt);
            }
        });
        getContentPane().add(IOANo, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 180, 130, 35));

        PatientID.setBackground(new java.awt.Color(49, 19, 50));
        PatientID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        PatientID.setForeground(new java.awt.Color(255, 255, 255));
        PatientID.setBorder(null);
        getContentPane().add(PatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 254, 200, 23));

        Name.setBackground(new java.awt.Color(49, 19, 50));
        Name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setBorder(null);
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 308, 200, 23));

        Type.setBackground(new java.awt.Color(49, 19, 50));
        Type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Type.setForeground(new java.awt.Color(255, 255, 255));
        Type.setBorder(null);
        getContentPane().add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(338, 364, 200, 23));

        Submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitMouseClicked(evt);
            }
        });
        getContentPane().add(Submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(477, 416, 53, 30));

        MouseClickBackPatientDashBoardRIGHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardRIGHTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 42, 308, 466));

        MouseClickBackPatientDashBoardBOTTOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardBOTTOMMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardBOTTOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 508, 900, 42));

        MouseClickBackPatientDashBoardLEFT.setPreferredSize(new java.awt.Dimension(310, 466));
        MouseClickBackPatientDashBoardLEFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardLEFTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        MouseClickBackPatientDashBoardTOP.setPreferredSize(new java.awt.Dimension(900, 42));
        MouseClickBackPatientDashBoardTOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardTOPMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardTOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AdminImg/AdminDashBoardReportGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitMouseClicked
        //new AdminDashBoardReportDetailsGUI().setVisible(true);
        JOptionPane.showMessageDialog(null, "Hi");
    }//GEN-LAST:event_SubmitMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void MouseClickBackPatientDashBoardRIGHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked

    private void MouseClickBackPatientDashBoardBOTTOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked

    private void MouseClickBackPatientDashBoardLEFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardLEFTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardLEFTMouseClicked

    private void MouseClickBackPatientDashBoardTOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardTOPMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardTOPMouseClicked

    private void TestIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TestIDItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            if(TestID.getSelectedIndex()>0){
            selected_TestID = TestID.getItemAt(TestID.getSelectedIndex());
            
            if(con != null) {
            try {
                ps = con.prepareStatement("SELECT type FROM TEST where t_id = ?");
                ps.setInt(1, Integer.valueOf(selected_TestID));
                rs = ps.executeQuery();
                
                rs.next();
                
                Type.setText(rs.getString(1));
                
                IOANo.removeAllItems();
                IOANo.addItem("Select IOA No");
                
                ps = con.prepareStatement("SELECT app_no FROM appointment where t_id = ?");
                ps.setInt(1, Integer.valueOf(selected_TestID));
                rs = ps.executeQuery();
                
                while(rs.next()) {
                    IOANo.addItem(String.valueOf(rs.getInt(1)));
                }
                
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
        }
        }
    }//GEN-LAST:event_TestIDItemStateChanged

    private void IOANoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_IOANoItemStateChanged
        if(evt.getStateChange() == ItemEvent.SELECTED) {
            if(IOANo.getSelectedIndex()>0){
            selected_App_No = IOANo.getItemAt(IOANo.getSelectedIndex());
            
            if(con != null) {
            try {
                ps = con.prepareStatement("SELECT name,a.p_id FROM appointment a, patient p where app_no = ? and a.p_id = p.p_id");
                ps.setInt(1, Integer.valueOf(selected_App_No));
                rs = ps.executeQuery();
                
                rs.next();
                
                Name.setText(rs.getString(1));
                PatientID.setText(rs.getString(2));
                
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
        }
        }
    }//GEN-LAST:event_IOANoItemStateChanged

    
    private void setIDField() {
        if(con != null) {
            try {
                ps = con.prepareStatement("SELECT * FROM TEST");
                rs = ps.executeQuery();
                
                while(rs.next()) {
                    TestID.addItem(String.valueOf(rs.getInt(1)));
                }
                
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBoardReportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBoardReportGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JComboBox<String> IOANo;
    private javax.swing.JLabel MouseClickBackPatientDashBoardBOTTOM;
    private javax.swing.JLabel MouseClickBackPatientDashBoardLEFT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardRIGHT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardTOP;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField PatientID;
    private javax.swing.JLabel Submit;
    private javax.swing.JComboBox<String> TestID;
    private javax.swing.JTextField Type;
    // End of variables declaration//GEN-END:variables
}
