/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.PatientGUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sajib
 */
public class PatientDashBoardGUI extends javax.swing.JFrame {

    int patientViewFlag = 1;
    
    public PatientDashBoardGUI() {
        initComponents();
        ProfileLabel.setEnabled(false);
        ProfileLabel.setVisible(false);
        PatientProfileClickLabel.setEnabled(false);
        PatientProfileClickLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AppointmentLabel = new javax.swing.JLabel();
        ViewAppointmentsLabel = new javax.swing.JLabel();
        ReportsLabel = new javax.swing.JLabel();
        ChangePasswordLabel = new javax.swing.JLabel();
        LogOutLabel = new javax.swing.JLabel();
        ClosedLabel = new javax.swing.JLabel();
        MinimizeLabel = new javax.swing.JLabel();
        ProfileLabel = new javax.swing.JLabel();
        PatientProfileLabel = new javax.swing.JLabel();
        PatientProfileClickLabel = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AppointmentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AppointmentLabelMouseClicked(evt);
            }
        });
        getContentPane().add(AppointmentLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 196, 140, 140));

        ViewAppointmentsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewAppointmentsLabelMouseClicked(evt);
            }
        });
        getContentPane().add(ViewAppointmentsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 196, 140, 140));

        ReportsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportsLabelMouseClicked(evt);
            }
        });
        getContentPane().add(ReportsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 196, 140, 140));

        ChangePasswordLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChangePasswordLabelMouseClicked(evt);
            }
        });
        getContentPane().add(ChangePasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 361, 140, 140));

        LogOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogOutLabelMouseClicked(evt);
            }
        });
        getContentPane().add(LogOutLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 361, 140, 140));

        ClosedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosedLabelMouseClicked(evt);
            }
        });
        getContentPane().add(ClosedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 8, 16, 16));

        MinimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseClicked(evt);
            }
        });
        getContentPane().add(MinimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 8, 16, 16));

        ProfileLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PatientImg/PateintDashbaordSettingGUI.png"))); // NOI18N
        getContentPane().add(ProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 161, 150, 60));

        PatientProfileLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientProfileLabelMouseClicked(evt);
            }
        });
        getContentPane().add(PatientProfileLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(836, 75, 38, 50));

        PatientProfileClickLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PatientProfileClickLabelMouseClicked(evt);
            }
        });
        getContentPane().add(PatientProfileClickLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 175, 113, 28));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PatientImg/PatientDashBoardGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AppointmentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AppointmentLabelMouseClicked
        new PatientDashBoardAppointmentGUI().setVisible(true);
    }//GEN-LAST:event_AppointmentLabelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void ViewAppointmentsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewAppointmentsLabelMouseClicked
        new PatientDashBoardViewAppointmentsGUI().setVisible(true);
    }//GEN-LAST:event_ViewAppointmentsLabelMouseClicked

    private void ClosedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosedLabelMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_ClosedLabelMouseClicked

    private void MinimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeLabelMouseClicked

    private void ReportsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportsLabelMouseClicked
        new PatientDashBoardReportsGUI().setVisible(true);
    }//GEN-LAST:event_ReportsLabelMouseClicked

    private void ChangePasswordLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChangePasswordLabelMouseClicked
        new PatientDashBoardChangePasswordGUI().setVisible(true);
    }//GEN-LAST:event_ChangePasswordLabelMouseClicked

    private void LogOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogOutLabelMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_LogOutLabelMouseClicked

    private void PatientProfileLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientProfileLabelMouseClicked
        if(patientViewFlag % 2 == 1) {
            ProfileLabel.setEnabled(true);
            ProfileLabel.setVisible(true);
            
            PatientProfileClickLabel.setEnabled(true);
            PatientProfileClickLabel.setVisible(true);
        }
        else {
            ProfileLabel.setEnabled(false);
            ProfileLabel.setVisible(false);
            
            PatientProfileClickLabel.setEnabled(false);
            PatientProfileClickLabel.setVisible(false);
        }
        
        patientViewFlag++;
    }//GEN-LAST:event_PatientProfileLabelMouseClicked

    private void PatientProfileClickLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PatientProfileClickLabelMouseClicked
        new PatientDashBoardProfileGUI().setVisible(true);
        
        ProfileLabel.setEnabled(false);
        ProfileLabel.setVisible(false);
        
        PatientProfileClickLabel.setEnabled(false);
        PatientProfileClickLabel.setVisible(false);
    }//GEN-LAST:event_PatientProfileClickLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashBoardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AppointmentLabel;
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JLabel ChangePasswordLabel;
    private javax.swing.JLabel ClosedLabel;
    private javax.swing.JLabel LogOutLabel;
    private javax.swing.JLabel MinimizeLabel;
    private javax.swing.JLabel PatientProfileClickLabel;
    private javax.swing.JLabel PatientProfileLabel;
    private javax.swing.JLabel ProfileLabel;
    private javax.swing.JLabel ReportsLabel;
    private javax.swing.JLabel ViewAppointmentsLabel;
    // End of variables declaration//GEN-END:variables
}
