/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.PatientGUI;

import Database.DBConnection;
import Model.Patient;
import Views.HomePagePatientLoginGUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author sajib
 */
public class PatientDashBoardProfileGUI extends javax.swing.JFrame {

    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    public PatientDashBoardProfileGUI() {
        initComponents();
        con = DBConnection.getConnection();
        displayPatientInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Name = new javax.swing.JTextField();
        ID = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        MobileNo = new javax.swing.JTextField();
        ClosedLabel = new javax.swing.JLabel();
        MinimizeLabel = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setBackground(new java.awt.Color(61, 33, 63));
        Name.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setBorder(null);
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 112, 388, 23));

        ID.setBackground(new java.awt.Color(110, 89, 111));
        ID.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(255, 255, 255));
        ID.setBorder(null);
        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 193, 388, 23));

        Email.setBackground(new java.awt.Color(110, 89, 111));
        Email.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setBorder(null);
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 261, 388, 23));

        Address.setBackground(new java.awt.Color(110, 89, 111));
        Address.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setBorder(null);
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 329, 388, 23));

        MobileNo.setBackground(new java.awt.Color(110, 89, 111));
        MobileNo.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        MobileNo.setForeground(new java.awt.Color(255, 255, 255));
        MobileNo.setBorder(null);
        getContentPane().add(MobileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(388, 397, 388, 23));

        ClosedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosedLabelMouseClicked(evt);
            }
        });
        getContentPane().add(ClosedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 8, 16, 16));

        MinimizeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizeLabelMouseClicked(evt);
            }
        });
        getContentPane().add(MinimizeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(842, 8, 16, 16));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PatientImg/PatientDashBoardProfileGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ClosedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClosedLabelMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_ClosedLabelMouseClicked

    private void MinimizeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizeLabelMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizeLabelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void displayPatientInfo() {
        if(con != null) {
            try {
                ps = con.prepareStatement("Select * from patient where p_id = ?");
                ps.setInt(1, Integer.valueOf(HomePagePatientLoginGUI.LogINPatientID));
                rs = ps.executeQuery();
                rs.next();
                Name.setText(rs.getString(2));
                ID.setText(String.valueOf(rs.getInt(1)));
                Email.setText(rs.getString(3));
                Address.setText(rs.getString(5));
                MobileNo.setText(rs.getString(4));
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardProfileGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashBoardProfileGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JLabel ClosedLabel;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel MinimizeLabel;
    private javax.swing.JTextField MobileNo;
    private javax.swing.JTextField Name;
    // End of variables declaration//GEN-END:variables
}
