/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.PatientGUI;
import Database.DBConnection;
import Views.HomePagePatientLoginGUI;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author sajib
 */
public class PatientDashBoardChangePasswordGUI extends javax.swing.JFrame {

    int verifyViewEyeFlag = 1;
    int newViewEyeFlag = 1;
    int currentViewEyeFlag = 1;
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public PatientDashBoardChangePasswordGUI() {
        initComponents();
        con = DBConnection.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MouseClickBackPatientDashBoardTOP = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardLEFT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardBOTTOM = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardRIGHT = new javax.swing.JLabel();
        VerifyPasswordEye = new javax.swing.JLabel();
        NewPasswordEye = new javax.swing.JLabel();
        CurrentPasswordEye = new javax.swing.JLabel();
        VerifyPasswordField = new javax.swing.JPasswordField();
        NewPasswordField = new javax.swing.JPasswordField();
        CurrentPasswordField = new javax.swing.JPasswordField();
        Ok = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MouseClickBackPatientDashBoardTOP.setPreferredSize(new java.awt.Dimension(900, 42));
        MouseClickBackPatientDashBoardTOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardTOPMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardTOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MouseClickBackPatientDashBoardLEFT.setPreferredSize(new java.awt.Dimension(310, 466));
        MouseClickBackPatientDashBoardLEFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardLEFTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        MouseClickBackPatientDashBoardBOTTOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardBOTTOMMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardBOTTOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 508, 900, 42));

        MouseClickBackPatientDashBoardRIGHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardRIGHTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 42, 308, 466));

        VerifyPasswordEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VerifyPasswordEyeMouseClicked(evt);
            }
        });
        getContentPane().add(VerifyPasswordEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 330, 16, 16));

        NewPasswordEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewPasswordEyeMouseClicked(evt);
            }
        });
        getContentPane().add(NewPasswordEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 251, 16, 16));

        CurrentPasswordEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CurrentPasswordEyeMouseClicked(evt);
            }
        });
        getContentPane().add(CurrentPasswordEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 174, 16, 16));

        VerifyPasswordField.setBackground(new java.awt.Color(49, 19, 50));
        VerifyPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        VerifyPasswordField.setBorder(null);
        getContentPane().add(VerifyPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 330, 181, 16));

        NewPasswordField.setBackground(new java.awt.Color(49, 19, 50));
        NewPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        NewPasswordField.setBorder(null);
        getContentPane().add(NewPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 251, 181, 16));

        CurrentPasswordField.setBackground(new java.awt.Color(49, 19, 50));
        CurrentPasswordField.setForeground(new java.awt.Color(255, 255, 255));
        CurrentPasswordField.setBorder(null);
        getContentPane().add(CurrentPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 174, 181, 16));

        Ok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OkMouseClicked(evt);
            }
        });
        getContentPane().add(Ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 386, 32, 30));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PatientImg/PatientDashboardChangePasswordGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClickBackPatientDashBoardTOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardTOPMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardTOPMouseClicked

    private void MouseClickBackPatientDashBoardLEFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardLEFTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardLEFTMouseClicked

    private void MouseClickBackPatientDashBoardBOTTOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked

    private void MouseClickBackPatientDashBoardRIGHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void VerifyPasswordEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerifyPasswordEyeMouseClicked
        if(verifyViewEyeFlag % 2 == 1)
        VerifyPasswordField.setEchoChar((char)0);
        else
        VerifyPasswordField.setEchoChar('*');
        verifyViewEyeFlag++;
    }//GEN-LAST:event_VerifyPasswordEyeMouseClicked

    private void NewPasswordEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewPasswordEyeMouseClicked
        if(newViewEyeFlag % 2 == 1)
        NewPasswordField.setEchoChar((char)0);
        else
        NewPasswordField.setEchoChar('*');
        newViewEyeFlag++;
    }//GEN-LAST:event_NewPasswordEyeMouseClicked

    private void CurrentPasswordEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CurrentPasswordEyeMouseClicked
        if(currentViewEyeFlag % 2 == 1)
        CurrentPasswordField.setEchoChar((char)0);
        else
        CurrentPasswordField.setEchoChar('*');
        currentViewEyeFlag++;
    }//GEN-LAST:event_CurrentPasswordEyeMouseClicked

    
    private boolean isValidCurPass() {
        try {
            ps = con.prepareStatement("Select password from patient where p_id = ?");
            ps.setInt(1, HomePagePatientLoginGUI.LogINPatientID);
            rs = ps.executeQuery();
            rs.next();
            if(rs.getString(1).equals(CurrentPasswordField.getText()))
                return true;
            else
                 return false;
        }
        catch(Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Query Execution Problem");
        return false;
    }
    
    
    
    private void OkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OkMouseClicked
        String pass1 = VerifyPasswordField.getText();
        String pass2 = NewPasswordField.getText();
        if(isValidCurPass()){
            if(pass1.equals(pass2)){
                if(con != null) {
                    try {
                        ps = con.prepareStatement("UPDATE `patient` SET `password`=? WHERE p_id = ?");
                        ps.setInt(2, Integer.valueOf(HomePagePatientLoginGUI.LogINPatientID));
                        ps.setString(1, pass1);

                        ps.executeUpdate();

                        JOptionPane.showMessageDialog(null,"Password Changed");
                        this.setVisible(false);
                    }
                    catch(Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }               
                }
                else
                    JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
            }else {
                JOptionPane.showMessageDialog(null, "Please Check Your Verify Password");
            }
        }else {
            JOptionPane.showMessageDialog(null, "Please Check Your Current Password");
        }
    }//GEN-LAST:event_OkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardChangePasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardChangePasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardChangePasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientDashBoardChangePasswordGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientDashBoardChangePasswordGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JLabel CurrentPasswordEye;
    private javax.swing.JPasswordField CurrentPasswordField;
    private javax.swing.JLabel MouseClickBackPatientDashBoardBOTTOM;
    private javax.swing.JLabel MouseClickBackPatientDashBoardLEFT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardRIGHT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardTOP;
    private javax.swing.JLabel NewPasswordEye;
    private javax.swing.JPasswordField NewPasswordField;
    private javax.swing.JLabel Ok;
    private javax.swing.JLabel VerifyPasswordEye;
    private javax.swing.JPasswordField VerifyPasswordField;
    // End of variables declaration//GEN-END:variables
}
