/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.PatientGUI;

import Database.DBConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class PatientSignUpGUI extends javax.swing.JFrame {

    int signUpPasswordViewFlag = 1;
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public PatientSignUpGUI() {
        initComponents();
        con = DBConnection.getConnection();
        setPatientIDField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientIDField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        MobileNoField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        PasswordEye = new javax.swing.JLabel();
        SignUp = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardTOP = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardLEFT = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardBOTTOM = new javax.swing.JLabel();
        MouseClickBackPatientDashBoardRIGHT = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientIDField.setBackground(new java.awt.Color(49, 19, 50));
        PatientIDField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PatientIDField.setForeground(new java.awt.Color(255, 255, 255));
        PatientIDField.setBorder(null);
        getContentPane().add(PatientIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 131, 200, 14));

        NameField.setBackground(new java.awt.Color(49, 19, 50));
        NameField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        NameField.setForeground(new java.awt.Color(255, 255, 255));
        NameField.setBorder(null);
        getContentPane().add(NameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 179, 200, 14));

        EmailField.setBackground(new java.awt.Color(49, 19, 50));
        EmailField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        EmailField.setForeground(new java.awt.Color(255, 255, 255));
        EmailField.setBorder(null);
        getContentPane().add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 227, 200, 14));

        MobileNoField.setBackground(new java.awt.Color(49, 19, 50));
        MobileNoField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        MobileNoField.setForeground(new java.awt.Color(255, 255, 255));
        MobileNoField.setBorder(null);
        getContentPane().add(MobileNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 323, 200, 14));

        AddressField.setBackground(new java.awt.Color(49, 19, 50));
        AddressField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        AddressField.setForeground(new java.awt.Color(255, 255, 255));
        AddressField.setBorder(null);
        getContentPane().add(AddressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 371, 200, 14));

        PasswordField.setBackground(new java.awt.Color(49, 19, 50));
        PasswordField.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        PasswordField.setForeground(new java.awt.Color(255, 255, 255));
        PasswordField.setBorder(null);
        getContentPane().add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 275, 182, 14));

        PasswordEye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordEyeMouseClicked(evt);
            }
        });
        getContentPane().add(PasswordEye, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 273, 16, 16));

        SignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SignUpMouseClicked(evt);
            }
        });
        getContentPane().add(SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(491, 408, 50, 31));

        MouseClickBackPatientDashBoardTOP.setPreferredSize(new java.awt.Dimension(900, 42));
        MouseClickBackPatientDashBoardTOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardTOPMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardTOP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MouseClickBackPatientDashBoardLEFT.setPreferredSize(new java.awt.Dimension(310, 466));
        MouseClickBackPatientDashBoardLEFT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardLEFTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardLEFT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 42, -1, -1));

        MouseClickBackPatientDashBoardBOTTOM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardBOTTOMMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardBOTTOM, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 508, 900, 42));

        MouseClickBackPatientDashBoardRIGHT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MouseClickBackPatientDashBoardRIGHTMouseClicked(evt);
            }
        });
        getContentPane().add(MouseClickBackPatientDashBoardRIGHT, new org.netbeans.lib.awtextra.AbsoluteConstraints(592, 42, 308, 466));

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PatientImg/PatientSignUpGUI.png"))); // NOI18N
        getContentPane().add(BackgroundImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 550));

        setSize(new java.awt.Dimension(900, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MouseClickBackPatientDashBoardTOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardTOPMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardTOPMouseClicked

    private void MouseClickBackPatientDashBoardLEFTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardLEFTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardLEFTMouseClicked

    private void MouseClickBackPatientDashBoardBOTTOMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardBOTTOMMouseClicked

    private void MouseClickBackPatientDashBoardRIGHTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_MouseClickBackPatientDashBoardRIGHTMouseClicked

    private void PasswordEyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordEyeMouseClicked
        if(signUpPasswordViewFlag % 2 == 1)
            PasswordField.setEchoChar((char)0);
        else
            PasswordField.setEchoChar('*');
        signUpPasswordViewFlag++;
    }//GEN-LAST:event_PasswordEyeMouseClicked
    
    private void SignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SignUpMouseClicked
        if(checkEmptyField()) {
            if(checkValidity()) {
                if(con != null) {
                    try {
                        ps = con.prepareStatement("INSERT INTO `patient`(`name`, `email`, `phone`, `Address`, `password`) VALUES (?,?,?,?,?)");
                        ps.setString(1, NameField.getText());
                        ps.setString(2, EmailField.getText());
                        ps.setString(3, MobileNoField.getText());
                        ps.setString(4, AddressField.getText());
                        ps.setString(5, PasswordField.getText());

                        ps.executeUpdate();
                    }
                    catch(Exception ex) {
                        JOptionPane.showMessageDialog(null, ex.getMessage());
                    }               
                }
                else
                    JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
                
                
                
                JOptionPane.showMessageDialog(null, "Account Created");
                this.setVisible(false);
            }
        }else {
            JOptionPane.showMessageDialog(null, "Please Fill Up All Data");
        }
    }//GEN-LAST:event_SignUpMouseClicked
    
    private void setPatientIDField() {
        if(con != null) {
            int count = 0;
            try {
                ps = con.prepareStatement("SELECT * FROM Patient");
                rs = ps.executeQuery();
                
                while(rs.next()) {
                    count++;
                }
                
                PatientIDField.setText(String.valueOf(3000+count));
            }
            catch(Exception ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }               
        }
        else
            JOptionPane.showMessageDialog(null, "DateBase Connection Failed");
    }
    
    private boolean checkEmptyField() {
        if(PatientIDField.getText().equals("") || NameField.getText().equals("") || EmailField.getText().equals("")
                || MobileNoField.getText().equals("") || AddressField.getText().equals("") || PasswordField.getText().equals(""))
            return false;
        return true;
    }
    private boolean checkValidity() {
        boolean flag = true;
        if(!emailValidity(EmailField.getText())){
            JOptionPane.showMessageDialog(null, "Please Input Valid Email Address");
            flag = false;
        }
        else if(PasswordField.getText().length()<8){
            JOptionPane.showMessageDialog(null, "Password length should be greater than 8");
            flag = false;
        }
        if(flag)
            return true;
        return false;
    }
    
    private boolean emailValidity(String email) {
        String regex = "^[\\w-_\\.+]*[\\w-_\\.]\\@([\\w]+\\.)+[\\w]+[\\w]$";
        return email.matches(regex);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for(double i=0.0; i<=1.0; i+=0.1) {
            String val = i+"";
            float fval = Float.valueOf(val);
            this.setOpacity(fval);
            try {
                Thread.sleep(50);
            }
            catch(Exception e) {
                
            }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PatientSignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PatientSignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PatientSignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PatientSignUpGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PatientSignUpGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField MobileNoField;
    private javax.swing.JLabel MouseClickBackPatientDashBoardBOTTOM;
    private javax.swing.JLabel MouseClickBackPatientDashBoardLEFT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardRIGHT;
    private javax.swing.JLabel MouseClickBackPatientDashBoardTOP;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel PasswordEye;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField PatientIDField;
    private javax.swing.JLabel SignUp;
    // End of variables declaration//GEN-END:variables
}
